os:
    - linux
    - osx
sudo: required
dist: trusty
language: objective-c
osx_image: xcode7.3
xcode_workspace: Cryptography.xcworkspace
xcode_scheme: Cryptography
podfile: Podfile
before_install: gem install cocoapods -v '= 1.0.0'
script:
- set -o pipefail
- xcodebuild -workspace Cryptography.xcworkspace -scheme Cryptography test -sdk macosx | xcpretty -c
- pod lib lint --quick